import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Docker Commands Cheat Sheet",
  description:
    "Essential Docker commands for containers, images, logs, networking, volumes, builds and troubleshooting.",
};
export default function DockerCommands() {
    const commands = [
      {
        command: "docker --version",
        description: "Check the installed Docker version.",
      },
      {
        command: "docker ps",
        description: "List currently running containers.",
      },
      {
        command: "docker ps -a",
        description: "List all containers, including stopped containers.",
      },
      {
        command: "docker images",
        description: "List Docker images available locally.",
      },
      {
        command: "docker pull nginx",
        description: "Download the nginx image from a container registry.",
      },
      {
        command: "docker run nginx",
        description: "Create and start a container from the nginx image.",
      },
      {
        command: "docker run -d nginx",
        description: "Run an nginx container in detached mode.",
      },
      {
        command: "docker run -d -p 8080:80 nginx",
        description: "Run nginx and map host port 8080 to container port 80.",
      },
      {
        command: "docker start <container>",
        description: "Start an existing stopped container.",
      },
      {
        command: "docker stop <container>",
        description: "Stop a running container.",
      },
      {
        command: "docker restart <container>",
        description: "Restart a container.",
      },
      {
        command: "docker rm <container>",
        description: "Remove a stopped container.",
      },
      {
        command: "docker rm -f <container>",
        description: "Force remove a running or stopped container.",
      },
      {
        command: "docker logs <container>",
        description: "View logs generated by a container.",
      },
      {
        command: "docker logs -f <container>",
        description: "Follow container logs in real time.",
      },
      {
        command: "docker exec -it <container> /bin/bash",
        description: "Open an interactive Bash shell inside a container.",
      },
      {
        command: "docker inspect <container>",
        description: "Display detailed information about a container.",
      },
      {
        command: "docker stats",
        description: "Monitor CPU, memory, network and other container resources.",
      },
      {
        command: "docker build -t myapp .",
        description: "Build a Docker image from a Dockerfile.",
      },
      {
        command: "docker rmi <image>",
        description: "Remove a Docker image.",
      },
      {
        command: "docker network ls",
        description: "List Docker networks.",
      },
      {
        command: "docker volume ls",
        description: "List Docker volumes.",
      },
      {
        command: "docker system df",
        description: "Show Docker disk usage.",
      },
      {
        command: "docker system prune",
        description: "Remove unused Docker resources.",
      },
    ];
  
    return (
      <main className="min-h-screen bg-slate-950 text-white">
        <div className="mx-auto max-w-5xl px-6 py-12">
          <a
            href="/"
            className="text-sm font-semibold text-cyan-400 hover:text-cyan-300"
          >
            ← Back to DevOpsToolbox
          </a>
  
          <header className="mt-8">
            <p className="text-sm font-semibold uppercase tracking-wider text-cyan-400">
              Docker
            </p>
  
            <h1 className="mt-3 text-4xl font-bold">
              Docker Commands Cheat Sheet
            </h1>
  
            <p className="mt-4 max-w-3xl text-slate-400">
              Essential Docker commands for containers, images, logs,
              networking, volumes and troubleshooting.
            </p>
          </header>
  
          <section className="mt-10 rounded-xl border border-slate-800 bg-slate-900 p-6">
            <h2 className="text-2xl font-bold">Essential Docker Commands</h2>
  
            <div className="mt-6 space-y-4">
              {commands.map((item) => (
                <div
                  key={item.command}
                  className="rounded-lg border border-slate-800 bg-slate-950 p-4"
                >
                  <code className="text-cyan-400">{item.command}</code>
  
                  <p className="mt-2 text-sm leading-6 text-slate-400">
                    {item.description}
                  </p>
                </div>
              ))}
            </div>
          </section>
  
          <section className="mt-8 rounded-xl border border-cyan-900 bg-slate-900 p-6">
            <h2 className="text-xl font-bold">Docker Troubleshooting Workflow</h2>
  
            <pre className="mt-4 overflow-x-auto rounded-lg bg-slate-950 p-4 text-sm text-slate-300">
  {`# Check running containers
  docker ps
  
  # Check all containers
  docker ps -a
  
  # Check container logs
  docker logs <container>
  
  # Follow logs
  docker logs -f <container>
  
  # Inspect container
  docker inspect <container>
  
  # Check resource usage
  docker stats
  
  # Check Docker disk usage
  docker system df`}
            </pre>
          </section>
  
          <section className="mt-8 rounded-xl border border-slate-800 bg-slate-900 p-6">
            <h2 className="text-xl font-bold">DevOpsToolbox Tip</h2>
  
            <p className="mt-3 leading-7 text-slate-400">
              When a container is not working, start with
              <code className="mx-1 text-cyan-400">docker ps -a</code>,
              then check its logs with
              <code className="mx-1 text-cyan-400">docker logs</code>.
              These two commands often reveal the problem quickly.
            </p>
          </section>
        </div>
      </main>
    );
  }